# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FedoraCommons-APIM
version:      0.1
version_from: lib/FedoraCommons/APIM.pm
installdirs:  site
requires:
    Carp:                          1.03
    HTML::Template:                2.9
    LWP:                           5.8
    MIME::Base64:                  3.03
    POSIX:                         1.08
    SOAP::Lite:                    0.67
    Test::Simple:                  0.44
    Time::HiRes:                   1.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
